#!/usr/bin/env python3
"""
generate_runoff_report.py — Build report/runoff_mapping.html from results/latest.json.

Runoff mapping gets its own page rather than a card on the mom6_forge page because
the numbers only mean something with the narrative attached: the destination grid
spans a factor of ~800 across the sweep and the wall time barely moves, which is a
finding about where the cost lives, not a row in a timing table.

Three sections:
  1. Domain ladder — gen_rof_maps() up an ascending destination-size ladder at
     fixed 1/12 deg, sub-real boxes first, then the real CROC domains.
  2. Resolution sweep — the same call at a fixed geographic footprint, so only
     the destination cell count varies.
  3. The 0/360 seam — why the boxes sit where they do, and the mom6_forge bbox
     bug that made this page briefly report a size cliff that does not exist.

Charts and the domain label table come from generate_report.py so the two pages
can't disagree about how a rung is named.

Output: report/runoff_mapping.html
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_FILE = REPO_ROOT / "results" / "latest.json"
OUTPUT_FILE = REPO_ROOT / "report" / "runoff_mapping.html"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_report import (  # noqa: E402
    ROF_DOMAIN_LABELS,
    _fmt_count,
    build_rof_domain_linechart,
    build_rof_resolution_linechart,
    build_tables,
    fmt_mb,
    fmt_time,
    load_benchmarks,
)
from report_common import LINECHART_CSS, page_shell, publish_results_json  # noqa: E402

PAGE = "runoff_mapping.html"
TITLE = "SeaSloth — Runoff mapping"
SUBTITLE = (
    "GLOFAS &rarr; ocean mapping file generation (<code>mom6_forge.gen_rof_maps</code>), "
    "one-time snapshot on Derecho/GLADE."
)
FOOTER = "Generated by scripts/generate_runoff_report.py"

RUNOFF_EXTRA_CSS = """
  .note { background: #fff8e6; border-left: 3px solid #d68c2a; border-radius: 4px;
          padding: 0.8rem 1rem; margin-bottom: 1.25rem; font-size: 0.85rem;
          color: #4a4438; }
  .note strong { color: #8a5a12; }
  td.pending { color: #b30000; font-weight: 600; }
"""


def _rows_for(grouped, test_name):
    return [
        r for r in grouped.get("mom6_forge", {}).get(test_name, []) if r.get("params")
    ]


def _detail_table(rows, key_label, key_of, sort_key):
    """Full numbers behind a chart: wall time, peak RSS, destination cell count."""
    if not rows:
        return "<p><em>No results yet.</em></p>"
    header = (
        f"<tr><th>{key_label}</th><th>Ocean cells</th><th>Mean</th>"
        "<th>Peak RSS</th></tr>"
    )
    body = "".join(
        f"<tr><td>{key_of(r)}</td>"
        f"<td>{_fmt_count(r['extra_info']['n_dst'])}</td>"
        f"<td>{fmt_time(r['stats']['mean'])}</td>"
        f"<td>{fmt_mb(r['extra_info'].get('peak_rss_mb'))}</td></tr>"
        for r in sorted(rows, key=sort_key)
    )
    return f"<table>{header}{body}</table>"


def _spread_sentence(rows, lead="Across the ladder"):
    """One sentence quantifying the headline finding, computed from the data
    rather than hard-coded, so it can't go stale when the sweep is re-run."""
    sized = [r for r in rows if r["extra_info"].get("n_dst")]
    if len(sized) < 2:
        return ""
    lo = min(sized, key=lambda r: r["extra_info"]["n_dst"])
    hi = max(sized, key=lambda r: r["extra_info"]["n_dst"])
    cell_factor = hi["extra_info"]["n_dst"] / lo["extra_info"]["n_dst"]
    time_factor = hi["stats"]["mean"] / lo["stats"]["mean"]
    return (
        f"{lead}, the destination grid grows "
        f"{cell_factor:,.0f}&times; "
        f"({_fmt_count(lo['extra_info']['n_dst'])} &rarr; "
        f"{_fmt_count(hi['extra_info']['n_dst'])} ocean cells) while wall time grows "
        f"{time_factor:.2f}&times; "
        f"({fmt_time(lo['stats']['mean'])} &rarr; {fmt_time(hi['stats']['mean'])})."
    )


def build_domain_section(grouped):
    rows = _rows_for(grouped, "test_gen_rof_maps_domain")
    if not rows:
        return "<section><p>No runoff domain-ladder results yet.</p></section>"

    chart = build_rof_domain_linechart(grouped)
    table = _detail_table(
        rows,
        "Domain",
        lambda r: ROF_DOMAIN_LABELS.get(
            r["extra_info"]["domain"], r["extra_info"]["domain"]
        ),
        lambda r: r["extra_info"]["n_dst"] or 0,
    )
    n_src = rows[0]["extra_info"].get("n_src")
    src_note = (
        f"the production GLOFAS mesh CIME registers as <code>ROF_DOMAIN_MESH</code> "
        f"({_fmt_count(n_src)} elements)"
        if n_src
        else "the production GLOFAS mesh"
    )
    return f"""
    <section>
      <h2>Cost vs. ocean domain size</h2>
      <p><code>gen_rof_maps()</code> builds the two mapping files CESM&rsquo;s DROF
         component needs to move river discharge onto the ocean grid — a
         nearest-neighbor map and a smoothed one. Every case here regrids from
         {src_note}, since that is the only source mesh a real case ever uses.</p>
      <p>The ladder starts well below any real configuration — a 1&deg; box, 144 ocean
         cells — and steps up roughly 4&times; per rung. The four <code>box_*</code> rungs
         are squares anchored at the Gulf of Mexico&rsquo;s southwest corner, so the small
         end of the sweep is a zoom-in on the smallest real configuration rather than an
         unrelated patch of ocean. From the Gulf of Mexico up, every rung is a domain
         CROC actually builds.</p>
      <div class="note"><strong>What the curve says:</strong> {_spread_sentence(rows)}
         Cost is essentially flat up to the Caribbean — 805&times; more cells for 1.02&times;
         the time — and only then begins to rise, mildly and roughly linearly. What
         dominates the small end is fixed source-mesh work: every source-domain field
         (<code>xc_a</code>, <code>yc_a</code>, <code>xv_a</code>, <code>mask_a</code>,
         <code>area_a</code>, &hellip;) is ~2.2&nbsp;GB and gets written into both output
         files, so a 1&deg; box pays nearly the same toll as a basin. The destination grid
         only starts to matter at basin scale, and even there it is a factor, not a wall.</div>
      {chart}
      <div class="card">
        <h3>Domain ladder — full numbers</h3>
        <p class="lc-sub">Fixed 1/12&deg; destination resolution, rmax = fold = 20 km.</p>
        {table}
      </div>
    </section>"""


def _monotonic_note(rows, order_key):
    """Whether time actually rises with the destination grid, said plainly.

    Computed rather than asserted in prose: on this sweep the ordering has come
    back non-monotonic, which is itself the finding (the spread is noise, not
    signal), and a hand-written claim about it would go stale the moment someone
    re-runs it.
    """
    times = [r["stats"]["mean"] for r in sorted(rows, key=order_key)]
    if len(times) < 2:
        return ""
    if all(b >= a for a, b in zip(times, times[1:])):
        return "Time does rise monotonically with the grid, but only barely."
    return "The ordering is not even monotonic — the spread is run-to-run noise."


def build_resolution_section(grouped):
    rows = _rows_for(grouped, "test_gen_rof_maps_resolution")
    if not rows:
        return ""
    chart = build_rof_resolution_linechart(grouped)
    table = _detail_table(
        rows,
        "Resolution",
        lambda r: f"1/{round(1 / r['params']['resolution_deg'])}&deg;",
        # By cell count, so the table reads in the same direction as the chart.
        lambda r: r["extra_info"]["n_dst"] or 0,
    )
    domain = rows[0]["extra_info"].get("domain", "")
    label = ROF_DOMAIN_LABELS.get(domain, domain)
    spread = _spread_sentence(rows, lead="Across the sweep")
    mono = _monotonic_note(rows, lambda r: r["extra_info"]["n_dst"] or 0)
    return f"""
    <section>
      <h2>Cost vs. ocean resolution</h2>
      <p>The same call over one fixed footprint ({label}), so the source/destination
         overlap window and the set of contributing rivers are constant and only the
         destination cell count changes. This separates &ldquo;how fine is the ocean
         grid&rdquo; from &ldquo;how much of the world does this domain touch&rdquo; —
         and it confirms the domain ladder&rsquo;s reading. {spread} {mono}</p>
      {chart}
      <div class="card">
        <h3>Resolution sweep — full numbers</h3>
        <p class="lc-sub">Fixed {label} footprint, rmax = fold = 20 km.</p>
        {table}
      </div>
    </section>"""


def build_seam_section():
    """The 0/360 seam hazard.

    Static prose, not derived from the JSON: it documents why the ladder's boxes
    sit where they do, and it is the reason this page briefly claimed a
    destination-size cliff that does not exist. Worth keeping visible even after
    the underlying mom6_forge bug is fixed, because the failure mode is silent.
    """
    return """
    <section>
      <h2>The 0/360 seam — why these boxes sit where they do</h2>
      <p>Every rung above is deliberately clear of the 0/360 periodic seam, and the
         benchmark asserts it at import. This page previously reported the two
         basin-scale rungs as intractable — &gt;1 hr at ~98% CPU in ESMF&rsquo;s
         <code>ESMP_FieldRegridStore</code> without completing. That was wrong, and the
         cause is worth writing down.</p>
      <div class="note"><strong>The bug:</strong> the North Atlantic box was
         <code>(xstart=280, lenx=80)</code>, and 280&nbsp;+&nbsp;80&nbsp;=&nbsp;360.
         <code>_get_mesh_bbox()</code> normalizes longitudes into [0,&nbsp;360), so the
         601 mesh nodes sitting on exactly 360 become 0 — and a naive
         <code>min()</code>/<code>max()</code> then returns a <em>near-global</em>
         longitude bounding box, <code>0.00 .. 359.92</code> instead of
         <code>280 .. 360</code>. That makes <code>generate_ESMF_map_via_xesmf</code>&rsquo;s
         <code>map_overlap</code> masking a no-op in longitude, so the regrid runs
         against the entire global 20–70&deg;N band rather than the domain&rsquo;s own
         80&deg; window. Shift the box 5&deg; west and the identical 576K-cell case
         finishes in 106&nbsp;s.</div>
      <p>There was never a destination-size cliff. Cost is flat to ~116K cells and then
         rises mildly with the grid — the 2.4M-cell Indo-Pacific rung is about 2.4&times;
         the 144-cell box, not orders of magnitude more. For comparison, the production
         <code>CrocIndoPacific_112</code> case (2.65M cells, 1.91M of them active after
         land masking) writes its nearest-neighbor map in ~210&nbsp;s, which lines up.</p>
      <p><strong>Status:</strong> open as a <code>mom6_forge</code> bug. A regional domain
         ending at lon 360 is a legitimate thing to configure, and today it produces an
         unexplained hang — no error, no memory growth, ~1&nbsp;GB RSS, one core pinned.
         The fix belongs in <code>_get_mesh_bbox()</code>, which needs a wrap-aware
         longitude range rather than <code>min</code>/<code>max</code> of normalized
         values. Same class of bug as the <code>normalize_deg(src_lat)</code> defect
         already fixed on that branch.</p>
    </section>"""


def build_html(grouped):
    body = (
        build_domain_section(grouped)
        + build_resolution_section(grouped)
        + build_seam_section()
    )
    return page_shell(
        PAGE,
        TITLE,
        SUBTITLE,
        body,
        FOOTER,
        extra_css=LINECHART_CSS + RUNOFF_EXTRA_CSS,
    )


def main():
    benchmarks = load_benchmarks()
    if not benchmarks:
        print(
            f"No benchmarks found in {RESULTS_FILE}. "
            "Run scripts/run_benchmarks.sh first.",
            file=sys.stderr,
        )
    grouped = build_tables(benchmarks)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(build_html(grouped))
    publish_results_json(RESULTS_FILE, OUTPUT_FILE.parent)
    print(f"Runoff mapping report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
