#!/usr/bin/env python3
"""
generate_scaling_report.py — Build a static HTML page from results/mom6_scaling.json.

Two sections:
  1. Location comparison — four 100×100 domains (Caribbean, Equatorial Pacific, Arctic,
     Antarctic) each run at NTASKS_OCN=20 and 40 on Derecho's develop queue.  One
     throughput chart + full table per domain, plus a cross-domain comparison table.
  2. Historical NTASKS sweep — the original Bahamas full-sweep data kept for reference.

Output: report/mom6_scaling.html
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_FILE = REPO_ROOT / "results" / "mom6_scaling.json"
OUTPUT_FILE = REPO_ROOT / "report" / "mom6_scaling.html"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_report import _linechart_svg  # noqa: E402
from report_common import LINECHART_CSS, page_shell, publish_results_json  # noqa: E402


def load_scaling():
    if not RESULTS_FILE.exists():
        return None
    with open(RESULTS_FILE) as f:
        return json.load(f)


def fmt_s(v):
    return f"{v:.1f} s" if v < 60 else f"{v / 60:.1f} min"


def make_table_html(points):
    if not points:
        return "<p><em>No results yet.</em></p>"
    baseline = min(points, key=lambda p: p["ntasks_ocn"])
    baseline_per_core = (
        baseline["throughput_sim_years_per_day"] / baseline["ntasks_ocn"]
    )
    rows = []
    for p in points:
        per_core = p["throughput_sim_years_per_day"] / p["ntasks_ocn"]
        efficiency = 100.0 * per_core / baseline_per_core
        rows.append(
            f"<tr><td>{p['ntasks_ocn']}</td>"
            f"<td>{p['throughput_sim_years_per_day']:.2f}</td>"
            f"<td>{fmt_s(p['tot_run_time_s'])}</td>"
            f"<td>{p['ocn_cost_pe_hrs']:.1f}</td>"
            f"<td>{efficiency:.0f}%</td></tr>"
        )
    return (
        "<table><tr><th>NTASKS_OCN</th><th>Throughput (sim-years/day)</th>"
        "<th>Total Run Time</th><th>OCN Cost (pe-hrs/sim-year)</th>"
        f"<th>Parallel efficiency (vs N={baseline['ntasks_ocn']})</th></tr>"
        f"{''.join(rows)}</table>"
    )


def build_domain_section(domain):
    points = sorted(domain.get("points", []), key=lambda p: p["ntasks_ocn"])
    name = domain["name"]
    grid = domain.get("grid", "")

    if points:
        chart_points = [
            (str(p["ntasks_ocn"]), p["throughput_sim_years_per_day"]) for p in points
        ]
        chart = _linechart_svg(
            chart_points, y_fmt=lambda v: f"{v:.1f} y/day", color="#2a78d6"
        )
    else:
        chart = "<p><em>No results yet.</em></p>"

    table = make_table_html(points)
    return f"""
    <div class="card">
      <h3>{name}</h3>
      <p class="lc-sub">{grid}</p>
      <p class="lc-sub">x-axis: NTASKS_OCN</p>
      {chart}
      {table}
    </div>"""


def make_comparison_table_html(domains):
    """One row per domain, columns = NTASKS points present across all domains."""
    all_ntasks = sorted(
        {p["ntasks_ocn"] for d in domains for p in d.get("points", [])}
    )
    if not all_ntasks:
        return "<p><em>No comparison data yet.</em></p>"

    header = "".join(f"<th>N={n}</th>" for n in all_ntasks)
    rows = []
    for d in domains:
        by_n = {p["ntasks_ocn"]: p["throughput_sim_years_per_day"] for p in d.get("points", [])}
        cells = "".join(
            f"<td>{by_n[n]:.2f}</td>" if n in by_n else "<td>—</td>"
            for n in all_ntasks
        )
        rows.append(f"<tr><td>{d['name']}</td>{cells}</tr>")

    return (
        "<table><tr><th>Domain</th>" + header + "</tr>"
        + "".join(rows) + "</table>"
    )


def build_html(data):
    if not data:
        body = "<section><p>No scaling results found.</p></section>"
        return page_shell(
            "mom6_scaling.html",
            "SeaSloth MOM6 Scaling Report",
            "Location-dependent scaling sweep on Derecho.",
            body,
            "Generated by scripts/generate_scaling_report.py",
            extra_css=LINECHART_CSS,
        )

    domains = data.get("domains", [])
    ref = data.get("reference_sweep")

    # --- Section 1: location comparison ---
    if domains:
        meta = (
            f"<p class='lc-sub'>Compset: <code>{data.get('compset', '?')}</code> &mdash; "
            f"machine: {data.get('machine', '?')}, queue: {data.get('queue', '?')} &mdash; "
            f"date range: {', '.join(data.get('date_range', []))}</p>"
        )
        domain_cards = "".join(build_domain_section(d) for d in domains)
        comparison = make_comparison_table_html(domains)
        location_section = f"""
    <section>
      <h2>Throughput by Geographic Location</h2>
      {meta}
      <p>Each domain is 100×100 grid points, flat 1000 m bathymetry, 10 vertical levels,
         run at NTASKS_OCN=20 and 40 on Derecho's develop queue (30-day simulation).
         Helen Kershaw's question: does MOM6/CESM throughput vary by where on Earth the
         domain sits?</p>
      <div class="card">
        <h3>Cross-domain comparison — throughput (sim-years/day)</h3>
        {comparison}
      </div>
      {domain_cards}
    </section>"""
    else:
        location_section = "<section><p>No location-comparison results yet.</p></section>"

    # --- Section 2: historical reference sweep ---
    if ref and ref.get("points"):
        ref_points = sorted(ref["points"], key=lambda p: p["ntasks_ocn"])
        ref_chart_pts = [
            (str(p["ntasks_ocn"]), p["throughput_sim_years_per_day"]) for p in ref_points
        ]
        ref_chart = _linechart_svg(
            ref_chart_pts, y_fmt=lambda v: f"{v:.1f} y/day", color="#6c757d"
        )
        ref_table = make_table_html(ref_points)
        ref_section = f"""
    <section>
      <h2>Reference: Bahamas Full NTASKS Sweep</h2>
      <p class="lc-sub">{ref.get('grid', '')} &mdash; queue: {ref.get('queue', '')}</p>
      <div class="card">
        <h3>Throughput vs. NTASKS_OCN (1–80 cores)</h3>
        <p class="lc-sub">x-axis: NTASKS_OCN</p>
        {ref_chart}
        {ref_table}
      </div>
    </section>"""
    else:
        ref_section = ""

    body = location_section + ref_section

    return page_shell(
        "mom6_scaling.html",
        "SeaSloth MOM6 Scaling Report",
        "Location-dependent scaling sweep on Derecho.",
        body,
        "Generated by scripts/generate_scaling_report.py",
        extra_css=LINECHART_CSS,
    )


def main():
    data = load_scaling()
    if not data:
        print(f"No scaling results found in {RESULTS_FILE}.", file=sys.stderr)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(build_html(data))
    publish_results_json(RESULTS_FILE, OUTPUT_FILE.parent)
    print(f"Scaling report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
