#!/usr/bin/env python3
"""
generate_health_report.py — Build a static HTML page from results/health.json
(written daily by the data-health job in .github/workflows/publish.yml, which
runs scripts/check_data_access.py inside the crocontainer image).

Output: report/health.html
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_FILE = REPO_ROOT / "results" / "health.json"
OUTPUT_FILE = REPO_ROOT / "report" / "health.html"


def load_health():
    if not RESULTS_FILE.exists():
        return {"date": None, "link_checks": [], "validate_checks": []}
    with open(RESULTS_FILE) as f:
        return json.load(f)


def _status(ok):
    return '<span class="ok">Yes</span>' if ok else '<span class="fail">No</span>'


def make_link_table(rows):
    if not rows:
        return "<p>No link checks recorded.</p>"
    body = "".join(
        f"<tr><td>{r['product']}</td><td>{r['url']}</td>"
        f"<td>{_status(r['ok'])}</td><td>{r['elapsed_s']:.1f}s</td></tr>"
        for r in sorted(rows, key=lambda r: r["product"])
    )
    return (
        "<table><tr><th>Product</th><th>URL</th><th>Reachable?</th><th>Elapsed</th></tr>"
        f"{body}</table>"
    )


def make_validate_table(rows):
    if not rows:
        return "<p>No validate_function checks recorded (CrocoDash not available when this ran).</p>"
    body = "".join(
        f"<tr><td>{r['product']}</td><td>{r['method']}</td>"
        f"<td>{_status(r['ok'])}</td><td>{r['elapsed_s']:.1f}s</td></tr>"
        for r in sorted(rows, key=lambda r: (r["product"], r["method"]))
    )
    return (
        "<table><tr><th>Product</th><th>Method</th><th>Working?</th><th>Elapsed</th></tr>"
        f"{body}</table>"
    )


def build_html(data):
    date = data.get("date") or "never run"
    link_checks = data.get("link_checks", [])
    validate_checks = data.get("validate_checks", [])
    link_ok = sum(1 for r in link_checks if r["ok"])
    val_ok = sum(1 for r in validate_checks if r["ok"])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SeaSloth Data Access Health</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 0; padding: 0; background: #f5f6fa; color: #222; }}
  header {{ background: #1a3a5c; color: #fff; padding: 1.5rem 2rem; }}
  header h1 {{ margin: 0 0 0.25rem; font-size: 1.6rem; }}
  header a {{ color: #9fc3e8; }}
  section {{ padding: 1.5rem 2rem 0.5rem; }}
  section h2 {{ font-size: 1.2rem; border-bottom: 2px solid #c8d6e5;
                padding-bottom: 0.4rem; margin-bottom: 1rem; color: #1a3a5c; }}
  .card {{ background: #fff; border-radius: 8px; padding: 1rem 1.25rem;
           box-shadow: 0 1px 4px rgba(0,0,0,0.1); overflow-x: auto; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.85rem; }}
  th, td {{ text-align: left; padding: 0.3rem 0.6rem; }}
  thead th {{ border-bottom: 2px solid #c8d6e5; color: #555; }}
  tbody tr:nth-child(even) {{ background: #f7f9fc; }}
  .ok {{ color: #1a7a3e; font-weight: 600; }}
  .fail {{ color: #b30000; font-weight: 600; }}
  footer {{ padding: 1.5rem 2rem; font-size: 0.8rem; color: #888; }}
</style>
</head>
<body>
<header>
  <h1>SeaSloth Data Access Health</h1>
  <p>As of {date} &mdash; links {link_ok}/{len(link_checks)} OK,
     functions {val_ok}/{len(validate_checks)} OK.
     <a href="index.html">&larr; Benchmark report</a> &middot;
     <a href="mom6_scaling.html">MOM6 scaling report &rarr;</a></p>
</header>
<section>
  <h2>Link checks</h2>
  <div class="card">{make_link_table(link_checks)}</div>
</section>
<section>
  <h2>validate_function checks</h2>
  <div class="card">{make_validate_table(validate_checks)}</div>
</section>
<footer>Generated by scripts/generate_health_report.py &mdash; refreshed daily by the data-health job in .github/workflows/publish.yml</footer>
</body>
</html>
"""


def main():
    data = load_health()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(build_html(data))
    print(f"Health report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
