#!/usr/bin/env python3
"""
generate_health_report.py — Build a static HTML page from results/health.json
(written daily by the data-health job in .github/workflows/publish.yml, which
runs scripts/check_data_access.py inside the crocontainer image).

Output: report/health.html
"""

import json
from pathlib import Path

from report_common import page_shell, publish_results_json

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_FILE = REPO_ROOT / "results" / "health.json"
OUTPUT_FILE = REPO_ROOT / "report" / "health.html"

# Health tables are mostly text (URLs, method names) — left-align every
# column instead of the shared shell's numeric-table default (right-aligned).
HEALTH_CSS = """
  .health-table th, .health-table td { text-align: left; }
"""


def load_health():
    if not RESULTS_FILE.exists():
        return {"date": None, "link_checks": [], "validate_checks": []}
    with open(RESULTS_FILE) as f:
        return json.load(f)


def _status(ok):
    return '<span class="ok">Yes</span>' if ok else '<span class="fail">No</span>'


def make_link_table(rows):
    if not rows:
        return "<p>No link checks recorded.</p>"
    body = "".join(
        f"<tr><td>{r['product']}</td><td>{r['url']}</td>"
        f"<td>{_status(r['ok'])}</td><td>{r['elapsed_s']:.1f}s</td></tr>"
        for r in sorted(rows, key=lambda r: r["product"])
    )
    return (
        "<table class='health-table'><tr><th>Product</th><th>URL</th>"
        f"<th>Reachable?</th><th>Elapsed</th></tr>{body}</table>"
    )


def make_validate_table(rows):
    if not rows:
        return "<p>No validate_function checks recorded (CrocoDash not available when this ran).</p>"
    body = "".join(
        f"<tr><td>{r['product']}</td><td>{r['method']}</td>"
        f"<td>{_status(r['ok'])}</td><td>{r['elapsed_s']:.1f}s</td></tr>"
        for r in sorted(rows, key=lambda r: (r["product"], r["method"]))
    )
    return (
        "<table class='health-table'><tr><th>Product</th><th>Method</th>"
        f"<th>Working?</th><th>Elapsed</th></tr>{body}</table>"
    )


def build_html(data):
    date = data.get("date") or "never run"
    link_checks = data.get("link_checks", [])
    validate_checks = data.get("validate_checks", [])
    link_ok = sum(1 for r in link_checks if r["ok"])
    val_ok = sum(1 for r in validate_checks if r["ok"])

    body = (
        "<section><h2>Link checks</h2>"
        f"<div class='card'>{make_link_table(link_checks)}</div></section>"
        "<section><h2>validate_function checks</h2>"
        f"<div class='card'>{make_validate_table(validate_checks)}</div></section>"
    )
    subtitle = (
        f"As of {date} &mdash; links {link_ok}/{len(link_checks)} OK, "
        f"functions {val_ok}/{len(validate_checks)} OK."
    )
    footer = (
        "Generated by scripts/generate_health_report.py &mdash; refreshed daily "
        "by the data-health job in .github/workflows/publish.yml"
    )
    return page_shell(
        "health.html",
        "SeaSloth Data Access Health",
        subtitle,
        body,
        footer,
        extra_css=HEALTH_CSS,
    )


def main():
    data = load_health()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(build_html(data))
    publish_results_json(RESULTS_FILE, OUTPUT_FILE.parent)
    print(f"Health report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
